rainbowwebsite/home/urls.py
from django.urls import path, include
from home import views
from home.sitemaps import StaticSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'home'

sitemaps = {'static': StaticSitemap}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('', views.index, name = 'index'),
    path('about/', views.aboutus, name = 'about'),
    path('signup/',  views.SignUpFormView.as_view(), name = 'signup'),
    path('success/', views.success, name="success"),
    path('terms/', views.terms, name="terms"),

    ]

rainbowwebsite/rainbowwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    # auth app is automatically installed in Django and doesnt need creations
    path('accounts/', include('django.contrib.auth.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('messages/', include('postman.urls', namespace='postman')),
    path('captcha/', include('captcha.urls')),
    path('posts/', include('posts.urls')),



    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rainbowwebsite/userprofile/urls.py
from django.urls import path, re_path
from userprofile import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'userprofile'

urlpatterns = [

    path('new/', views.NewUserProfileView.as_view(), name = 'newprofile'),
    path('users/<int:pk>/edit/', views.EditUserProfileView.as_view(), name="editprofile"),
    path('search/', views.profiles_list, name="profilesearch"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.profile_details, name="profileview"),
    re_path(r'^del/(?P<slug>\w+)/$', views.UserProfileDelete.as_view(), name="deleteprofile"),
    re_path(r'^report/(?P<slug>\w+)/$', views.contact, name="report"),
    


    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rainbowwebsite/userprofile/models.py
from django.db import models
from django_countries.fields import CountryField
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User
from django.utils.text import slugify
from datetime import datetime
from django.core.validators import MinValueValidator, MaxValueValidator




# Create your models here.

class UserProfiles(models.Model):

    LOOKING_CHOICES = (('gay man looking for another gay man', 'gay man looking for another gay man'),
              ('bisexual man looking for men and women', 'bisexual man looking for men and women'),
              ('gay man looking for a lesbian wife', 'gay man looking for a lesbian wife'),
              ('lesbian woman looking for another lesbian woman', 'lesbian woman looking for another lesbian woman'),
              ('bisexual woman looking for both men and women', 'bisexual woman looking for both men and women'),
              ('lesbian woman looking for a gay husband', 'lesbian woman looking for a gay husband'),
              ('trans/intersex looking for females', 'trans/intersex looking for females'),
              ('trans/intersex looking for males', 'trans/intersex looking for males'),
              ('male looking for trans/intersex', 'male looking for trans/intersex'),
              ('female looking for trans/intersex', 'female looking for trans/intersex'),
              ('Looking for anyone for friendship', 'Looking for anyone for friendship'),
              ('Looking to co-parent', 'Looking to co-parent'),
              )

    ETHNIC_CHOICES = (
        ('Indian', 'Indian'),
        ('Pakistani', 'Pakistani'),
        ('Bangladeshi', 'Bangladeshi'),
        ('Sri Lankan', 'Sri Lankan'),
        ('Arab', 'Arab'),
        ('White', 'White'),
        ('Black', 'Black'),
        ('Asian', 'Asian'),
        ('other', 'other'))


    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Transgender', 'Transgender'),
        ('Intersex', 'Intersex'),
        ('Non-Binary', 'Non-Binary'),
        ('Rather not say', 'Rather not say'))




    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=50)
    age= models.IntegerField(null=True, blank=True, validators=[MinValueValidator(18), MaxValueValidator(110)])
    Nationality= models.CharField(max_length=100, null=True, blank=True, verbose_name = 'Ethnicity:', choices = ETHNIC_CHOICES)
    image= models.ImageField(upload_to = 'pic_folder/', null=True, blank=False, verbose_name="your profile photo (required):")
    height= models.IntegerField(blank=True, null=True, verbose_name = "your height in cms:")
    weight= models.IntegerField(blank=True, null=True, verbose_name = 'Your weight in kgs:')
    description= models.TextField(max_length=500, verbose_name = 'Introduce yourself:')
    lookingfor= models.TextField(max_length=500, verbose_name= 'Your ideal soulmate:')
    preference = models.CharField(max_length=300, choices=LOOKING_CHOICES, verbose_name= "Preference:", null=True)
    Country = CountryField()
    City = models.CharField(verbose_name= 'city', max_length=120, null=True, blank = True)
    hobbies= models.CharField(max_length=200, null=True, blank=True)
    profession= models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField(null=True, default=datetime.now)



    def __str__(self):
        return str(self.user)

    def summary(self):
        return self.description[:150]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user)
        super(UserProfiles, self).save(*args, **kwargs)

rainbowwebsite/userprofile/forms.py
from userprofile.models import UserProfiles
from django import forms


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfiles
        fields = ('gender', 'age', 'Nationality','image', 'height', 'weight', 'description', 'lookingfor', 'preference',
        'Country', 'City', 'hobbies', 'profession')

    def save(self, user=None):
        user_profile = super(UserProfileForm, self).save(commit=False)
        if user:
            user_profile.user = user
        user_profile.save()
        return user_profile

class ContactForm(forms.Form):
    Username = forms.CharField(required=True)
    Reason = forms.CharField(required=True, max_length=200)
    Explanation = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

rainbowwebsite/userprofile/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, FormView, DetailView, ListView, DeleteView
from userprofile.forms import UserProfileForm, ContactForm
from userprofile.models import UserProfiles
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from userprofile.filters import UserProfilesFilter
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import redirect

# Create your views here.

class NewUserProfileView(FormView,LoginRequiredMixin):
    template_name = "userprofile/user_profile.html"
    form_class = UserProfileForm

    def form_valid(self, form):
        try:
            form.save(self.request.user)
            return super(NewUserProfileView, self).form_valid(form)
        except IntegrityError:
            return HttpResponse("You have already created a profile, please click back and click on My Profile.")

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy("home:index")


class EditUserProfileView(UpdateView, LoginRequiredMixin):

    model = UserProfiles
    form_class = UserProfileForm
    template_name = "userprofile/user_profile.html"
    slug_field = 'slug'

    def get_object(self, *args, **kwargs):

        user = get_object_or_404(User, pk=self.kwargs['pk'])
        return user.userprofiles

        def form_valid(self, form):
            print(form.cleaned_data)
            return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
         return reverse_lazy('home:index')


@login_required
def profiles_list(request):
    filter = UserProfilesFilter(request.GET, queryset = UserProfiles.objects.all().order_by('-pub_date'))
    return render(request,"userprofile/user_list.html", {'filter': filter})

@login_required
def profile_details(request,slug):
    profile = get_object_or_404(UserProfiles, slug=slug)
    return render(request, 'userprofile/profile_detail.html', {'profile': profile})

class UserProfileDelete(DeleteView, LoginRequiredMixin):
    model = UserProfiles
    success_url = reverse_lazy('home:index')
    template_name = "userprofile/profile_delete.html"

     # override the delete function to check for a user match
    def delete(self, request, *args, **kwargs):
        # the Post object
        self.object = self.get_object()
        if self.object.user == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            return HttpResponse("Cannot delete other's profiles")


def contact(request, slug):

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            Username = form.cleaned_data['Username']
            Reason = form.cleaned_data['Reason']
            Explanation = form.cleaned_data['Explanation']
            try:
                send_mail(Username,Explanation, 'report@rainbowsaathimail.com', ['rainbowsaathimail@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('home:success')
    return render(request, "userprofile/report.html", {'form': form})

rainbowwebsite/templates/userprofile/profile_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <br>
    <h1>Delete Your Profile</h1>
    <br><br>
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <br>
    <p>Alternatively, you can <a href="{% url 'userprofile:editprofile' user.pk %}">Edit Profile.</a> </p>
    <br>
    <input type="submit" value="Confirm">
</form>
</div>
{% endblock %}

rainbowwebsite/templates/userprofile/profile_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
  <div class="col-lg-10 col-md-6 col-sm-4 col-xs-4">
{% if request.user == profile.user %}
<button type="button" name="button"> <a href="{% url 'userprofile:editprofile' user.pk %}">Edit Profile</a></button>
<button type="button" name="button"> <a href="{% url 'postman:inbox' %}">My Inbox</a></button>
<button type="button" name="button"> <a href="{% url 'postman:sent' %}">Sent Messages</a></button>
<button type="button" name="button"> <a href="{% url 'postman:archives' %}">Archived Messages</a></button>
<button type="button" name="button"> <a href="{% url 'postman:trash' %}">Deleted Messages</a></button>
<button type="button" name="button"> <a href="{% url 'postman:write' %}">Write to a User</a></button>
<button type="button" name="button"> <a href="{% url 'userprofile:deleteprofile' user %}">Delete Profile</a></button>

{% else %}
<button type="button" class="btn btn-warning float-right rounded"><a href="{% url 'postman:write' profile.user %}">Message</a></button>
<button type="button" class="btn btn-danger float-right rounded"><a href="{% url 'userprofile:report' profile.user %}">Report</a></button>
{% endif %}
  </div>
<br><br>

  <h2>{{ profile.user }}</h2>
  <hr>
<img class="img-thumbnail img-responsive rounded float" Height="200" width="200" src="{{ profile.image.url }}" alt='cant display'>
<br><br>
<h5>Gender: {{ profile.gender}}</h5>
<h5>Age: {{ profile.age}}</h5>
<h5>Ethnicity: {{ profile.Nationality}}</h5>
{% if profile.height %}
<h5>Height: {{ profile.height}}</h5>
{% endif %}
{% if profile.weight %}
<h5>Weight: {{ profile.weight}}</h5>
{% endif %}
{% if profile.weight %}
<h5>City: {{ profile.City}}</h5>
{% endif %}
<h5>Country: {{ profile.Country}}</h5>
<br>
<p>{{ profile.preference}}</p>
<br>
<p> <strong>My Introduction:</strong>{{ profile.description|linebreaks}}</p>
<br>
<p><strong>My idea soulmate:</strong> {{ profile.lookingfor|linebreaks}}</p>
<br>
{% if profile.hobbies %}
<p> <strong>My hobbies:</strong>{{ profile.hobbies|linebreaks}}</p>
{% endif %}
{% if profile.profession %}
<p> <strong>My profession:</strong>{{ profile.profession|linebreaks}}</p>
{% endif %}



</div>

{% endblock %}

rainbowwebsite/templates/userprofile/report.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap %}

<div class="container">

<h1>Report User</h1>
<form role="form" action="" method="post" class="form-horizontal">
  <br>
  Please be as thorough as possible.
  <br>
<br>
  {{user}}, please type in, 'username' field below to confirm you are reporting the correct person. You should be able to see that
  in the URL link of your browser above. Please choose from reasons below, and give an explanation as to what the user did. Below are the list of reasons you can use when reporting a profile. Please note that in order to protect your privacy, this user will be reported to our team anonymously. <br>

<br>
<ul>
<li>Spam</li>
<li>Offensive or Abusive</li>
<li>Impersonation</li>
<li>	Buying and selling of goods and services</li>
<li>Under age</li>
<li>Pornographic material</li>
<li>Bullying/Harrassment</li>
</ul>
<br>
 <br>

    {% csrf_token %}
    {{ form|bootstrap }}
<br>
    <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

rainbowwebsite/templates/userprofile/user_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load bootstrap %}


<div class="container">

  <form class="form-horizontal col-md-4 col-lg-4 col-sm-4" action="" method="get">
        {{ filter.form|bootstrap}} {% csrf_token %}
        <input type="submit" value='search'/>
    </form>

  {% for profile in filter.qs %}
 <div class="col-md-10 col-lg-10 col-sm-8">


  <hr>

  <a href="{% url 'userprofile:profileview' profile.user %}"><h3>{{ profile.user }}</h3></a>
<br>
  <img src="{{ profile.image.url }}" class="rounded mx-auto d-block img-responsive float-left" style= "max-height: 100px; max-width: 100px;">
  <br><br>
  <br><br> <br>
  <div class="font-weight-normal text-justify">
  Gender: {{ profile.gender }}
<br>
  Country: {{ profile.Country }}
  <br>
  Description: {{ profile.summary }}
  <br>
  Preferences: {{ profile.preference }}
  <br>

  {% endfor %}


  </div>
    </div>
     </div>

  {% endblock %}

rainbowwebsite/templates/userprofile/user_profile.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap %}
<br>
<div class="container" class="form-horizontal">

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|bootstrap }}
<br>
  <input type=submit value="submit" />
</form>

</div>

{% endblock %}