rainbowwebsite/home/urls.py
from django.urls import path, include
from home import views
from home.sitemaps import StaticSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'home'

sitemaps = {'static': StaticSitemap}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('', views.index, name = 'index'),
    path('about/', views.aboutus, name = 'about'),
    path('signup/',  views.SignUpFormView.as_view(), name = 'signup'),
    path('success/', views.success, name="success"),
    path('terms/', views.terms, name="terms"),

    ]

rainbowwebsite/posts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

app_name = 'posts'

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('', views.postshome, name='postshome'),
    path('create/', views.post_new, name='create'),
    re_path(r'^del/(?P<pk>\w+)/$', views.PostDelete.as_view(), name="deletepost"),
]

rainbowwebsite/rainbowwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    # auth app is automatically installed in Django and doesnt need creations
    path('accounts/', include('django.contrib.auth.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('messages/', include('postman.urls', namespace='postman')),
    path('captcha/', include('captcha.urls')),
    path('posts/', include('posts.urls')),



    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rainbowwebsite/userprofile/urls.py
from django.urls import path, re_path
from userprofile import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'userprofile'

urlpatterns = [

    path('new/', views.NewUserProfileView.as_view(), name = 'newprofile'),
    path('users/<int:pk>/edit/', views.EditUserProfileView.as_view(), name="editprofile"),
    path('search/', views.profiles_list, name="profilesearch"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.profile_details, name="profileview"),
    re_path(r'^del/(?P<slug>\w+)/$', views.UserProfileDelete.as_view(), name="deleteprofile"),
    re_path(r'^report/(?P<slug>\w+)/$', views.contact, name="report"),
    


    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rainbowwebsite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">

      <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'images/rainbow.ico' %}"/>




<title>Rainbow Saathi</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home:index' %}">  <img src="{% static "images/rainbow.jpg" %}" width="100" height="100" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:about' %}">About Us <span class="sr-only">(current)</span></a>
            </li>
            {% if user.userprofiles %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:profileview' user %}">My Account</a>
          </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'postman:inbox' %}">Inbox</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:postshome' %}">Micro Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'userprofile:profilesearch' %}">Search</a>
      </li>
       {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:newprofile' %}">Create New Profile</a>
       {% endif %}  <!-- login/logout dont need namespace app -->
       <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            	{% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:about' %}">About Us <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <!-- login/logout dont need namespace app -->
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            <li>
              {% endif %}
          </ul>
        </div>
      </nav>


      </div>


      {% block content %}
          {% endblock %}


  </div>

  </body>

</html>