rainbowwebsite/home/urls.py
from django.urls import path, include
from home import views
from home.sitemaps import StaticSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'home'

sitemaps = {'static': StaticSitemap}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('', views.index, name = 'index'),
    path('about/', views.aboutus, name = 'about'),
    path('signup/',  views.SignUpFormView.as_view(), name = 'signup'),
    path('success/', views.success, name="success"),
    path('terms/', views.terms, name="terms"),

    ]

rainbowwebsite/posts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

app_name = 'posts'

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('', views.postshome, name='postshome'),
    path('create/', views.post_new, name='create'),
    re_path(r'^del/(?P<pk>\w+)/$', views.PostDelete.as_view(), name="deletepost"),
]

rainbowwebsite/rainbowwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    # auth app is automatically installed in Django and doesnt need creations
    path('accounts/', include('django.contrib.auth.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('messages/', include('postman.urls', namespace='postman')),
    path('captcha/', include('captcha.urls')),
    path('posts/', include('posts.urls')),



    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rainbowwebsite/userprofile/urls.py
from django.urls import path, re_path
from userprofile import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'userprofile'

urlpatterns = [

    path('new/', views.NewUserProfileView.as_view(), name = 'newprofile'),
    path('users/<int:pk>/edit/', views.EditUserProfileView.as_view(), name="editprofile"),
    path('search/', views.profiles_list, name="profilesearch"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.profile_details, name="profileview"),
    re_path(r'^del/(?P<slug>\w+)/$', views.UserProfileDelete.as_view(), name="deleteprofile"),
    re_path(r'^report/(?P<slug>\w+)/$', views.contact, name="report"),
    


    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rainbowwebsite/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100, null=True)
    url = models.TextField( max_length=450,null=True, verbose_name="")
    pub_date = models.DateTimeField(null=True, default=datetime.now())
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def publish(self):
        self.pub_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:postshome')

rainbowwebsite/posts/forms.py
from posts.models import Post
from django import forms


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'url')

rainbowwebsite/posts/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from posts.models import Post
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.forms import PostForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

# Create your views here.

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect(reverse_lazy('posts:postshome'))
    else:
        form = PostForm()
    return render(request, 'posts/create.html', {'form': form})


def postshome(request):
    posts = Post.objects.order_by('-pub_date')
    return render(request, 'posts/posthome.html', {'posts':posts})


class PostDelete(DeleteView, LoginRequiredMixin):
    model = Post
    success_url = reverse_lazy('posts:postshome')
    template_name = "posts/post_delete.html"

     # override the delete function to check for a user match
    def delete(self, request, *args, **kwargs):
        # the Post object
        self.object = self.get_object()
        if self.object.author == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            return HttpResponse("Cannot delete other's profiles")

rainbowwebsite/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap %}
<div class="container">

<h1>New Post</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form class="form-horizontal" method="POST">
  {% csrf_token %}
{{form|bootstrap}}
  <input class="btn btn-primary" type="submit" value="Post">
</form>
</div>
{% endblock %}

rainbowwebsite/templates/posts/post_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <br>
    <h1>Delete Your Post</h1>
    <br><br>
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <br>
    <input type="submit" value="Confirm">
</form>
</div>
{% endblock %}

rainbowwebsite/templates/posts/posthome.html
{% extends 'base.html' %}

{% block content %}
<div class="container">


<h1>Micro Posts</h1>
<br>
Micro Posts are a quick and short way to advertise yourself to other users. Add in a title and a short description of what you are looking for. The username of the micro post is the same as your profile username. Others can contact you directly, by clicking on your profile name in the micro post section. Please note that inappropriate posts will be deleted. Please refer to our <a href="{% url 'home:terms' %}">T&C</a> page for site policies.
<br><br>
<a class="btn btn-primary" href="{% url 'posts:create' %}">New Post</a>

<br/>
<br/>

{% for post in posts %}

<hr>

{{post.title}}

{% if request.user == post.author %}
<button type="button" class="btn btn-danger float-right rounded"><a href="{% url 'posts:deletepost' post.pk %}">Delete</a></button>
<br>
{% endif %}
{{post.url|linebreaksbr }}

<br><br>
<a href="{% url 'userprofile:profileview' post.author %}">{{ post.author }}</a>
<br> <br>

{{ post.pub_date }}


{% endfor %}

</div>


{% endblock %}